# Generated by Django 3.2.5 on 2021-07-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilestatus',
            old_name='user_profie',
            new_name='user_profile',
        ),
    ]
