# Generated by Django 3.2.5 on 2021-07-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('publication_date', models.DateField()),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
