# Generated by Django 3.2.5 on 2021-07-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210708_0741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journallist',
            table='journallists',
        ),
    ]
